version: '3.7'

volumes:
  results:

services:
  httpd:
    image: httpd
    build:
      context: ./httpd
      dockerfile: ./httpd.Dockerfile
    privileged: true
    container_name: httpd
  httpd_load_tester:
    image: httpd_load_tester
    build:
      context: ./httpd_load_tester
      dockerfile: ./httpd_load_tester.Dockerfile
    container_name: httpd_load_tester
    links:
      - "httpd:httpd"
    volumes:
      - "./results:/results:rw"
    depends_on:
      - httpd
